[[block]]
block = "speedtest"
format = " ↓ $speed_down ↑ $speed_up "
interval = 1800

[[block]]
block = "memory"
format = " $icon $mem_used "
format_alt = " $icon $swap_used_percents "
interval = 3

[[block]]
block = "cpu"
interval = 3

[[block]]
block = "temperature"
scale = "celsius"
format = " $icon $average "
interval = 3

[[block]]
block = "battery"
format = " $icon $percentage "
interval = 1

[[block]]
block = "backlight"
format = " $icon $brightness "

[[block]]
block = "sound"
format = " $icon $volume "

[[block]]
block = "time"
format = " $icon $timestamp.datetime(f:'%a %d-%m %T') "
interval = 1

[icons]
icons = "material-nf"

[theme]
theme = "space-villain"
